name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  schedule:
    - cron: "0 0 * * *"

#env:
#  CFLAGS: -Werror
#  USE_NET: 1

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build & Analyze
      run: make CFLAGS="-Werror -fanalyzer" lib all
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        retention-days: 5
        name: rvvm_linux_x86_64
        path: |
          release.linux.x86_64/rvvm_x86_64
          release.linux.x86_64/librvvm.so

  win32-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up MinGW
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends gcc-mingw-w64-x86-64-win32
    - name: Build & Analyze
      run: make CC=x86_64-w64-mingw32-gcc CFLAGS="-Werror -fanalyzer" all lib
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        retention-days: 5
        name: rvvm_win32_x86_64
        path: |
          release.windows.x86_64/rvvm_x86_64.exe
          release.windows.x86_64/librvvm.dll
        
  macos-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install SDL
        run: brew install sdl12-compat
      - name: Build
        run: make CFLAGS="-Werror" all lib
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          retention-days: 5
          name: rvvm_darwin_x86_64
          path: |
            release.darwin.x86_64/rvvm_x86_64
            release.darwin.x86_64/librvvm.so
